import { getRiderStats } from "../../api/riderApi";
import Container from "../../components/layout/Container";
import { useApiQuery } from "../../hooks/useApiQuery";

import { Link } from "react-router-dom";
import { Wallet, CheckCircle2, Clock, ShieldCheck } from "lucide-react";
import toast from "react-hot-toast";

const RiderStatsPage = () => {
  const { data, loading, error } = useApiQuery(getRiderStats, true);

  const metrics = [
    { label: 'Weekly Earnings', value: '₹4,850', sub: '+12% from last cycle', icon: Wallet },
    { label: 'Successful Handovers', value: data?.totalCollected ?? 0, sub: '99.8% Success Rate', icon: CheckCircle2 },
    { label: 'Avg. Turnaround', value: '72m', sub: 'Industry Rank: top 5%', icon: Clock },
    { label: 'Trust Coefficient', value: '98/100', sub: 'Verified across 42 lots', icon: ShieldCheck }
  ];

  const onDownloadLedger = () => {
    const content = `MEDAIMART LOGISTICS\nTAX LEDGER: CYCLE AUDIT\nDate: ${new Date().toLocaleDateString()}\n----------------------------------------\n\nRevenues:\t\t₹12,400\nDeductions:\t\t₹0.00\nNet Disbursal:\t\t₹12,400\n\n----------------------------------------\nGenerated by MedAImart Fleet Terminal`;
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `tax_ledger_${new Date().toISOString().split('T')[0]}.txt`);
    document.body.appendChild(link);
    link.click();
    link.remove();
    URL.revokeObjectURL(url);
    toast.success("Ledger downloaded successfully.");
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-muted/30 animate-pulse">
        <Container className="py-12">
          <div className="h-40 bg-card rounded-xl mb-8 border border-border" />
          <div className="grid md:grid-cols-2 gap-6">
            <div className="h-64 bg-card rounded-xl border border-border" />
            <div className="h-64 bg-card rounded-xl border border-border" />
          </div>
        </Container>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-muted/30 pb-20">
      <Container className="py-8 lg:py-12">
        {/* Header */}
        <div className="mb-10 font-sans">
          <Link to="/rider" className="inline-flex items-center gap-2 text-[9px] font-bold text-muted-foreground hover:text-primary transition-colors uppercase tracking-[0.2em] mb-6">
            <span className="tracking-widest opacity-60">BACK TO</span> COMMAND
          </Link>
          <div className="flex flex-col md:flex-row md:items-end justify-between gap-6">
            <div>
              <div className="flex items-center gap-2 text-[9px] font-bold text-primary uppercase tracking-[0.2em] mb-1.5 opacity-60">
                Performance Ledger
              </div>
              <h1 className="text-2xl lg:text-3xl font-serif font-bold text-foreground tracking-tight">
                Logistics <span className="text-primary">Efficacy</span>
              </h1>
              <p className="text-[11px] text-muted-foreground mt-1.5 font-sans font-medium opacity-70">
                Audit your collection performance and financial distributions.
              </p>
            </div>
          </div>
        </div>

        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-8 font-sans">
          {metrics.map((m, i) => (
            <div key={i} className="bg-card rounded-xl p-8 border border-border shadow-sm group hover:border-primary/20 transition-all">
              <div className="w-10 h-10 bg-foreground text-background rounded-xl flex items-center justify-center mb-6">
                <m.icon size={18} strokeWidth={2.5} />
              </div>
              <p className="text-[9px] font-bold text-muted-foreground uppercase tracking-widest mb-1 opacity-60">{m.label}</p>
              <div className="text-2xl font-bold text-foreground mb-1 tracking-tight">{m.value}</div>
              <p className="text-[9px] text-muted-foreground font-bold uppercase tracking-widest opacity-40">
                {m.sub}
              </p>
            </div>
          ))}
        </div>

        <div className="grid lg:grid-cols-3 gap-8">
          {/* Activity Chart Placeholder */}
          <div className="lg:col-span-2 bg-card rounded-xl p-8 lg:p-10 border border-border shadow-sm font-sans">
            <div className="flex items-center justify-between mb-10">
              <h3 className="text-[9px] font-bold text-foreground uppercase tracking-[0.2em] opacity-80">Distribution Cycle</h3>
              <div className="flex gap-2 font-sans">
                <span className="px-3 py-1 bg-muted rounded-lg text-[8px] font-bold text-muted-foreground uppercase">L_Wk</span>
                <span className="px-3 py-1 bg-primary text-primary-foreground rounded-lg text-[8px] font-bold shadow-lg shadow-primary/5 uppercase">T_Wk</span>
              </div>
            </div>

            {/* Simulated Bars */}
            <div className="flex items-end justify-between h-48 gap-4 px-4">
              {[40, 70, 45, 90, 65, 80, 55].map((h, i) => (
                <div key={i} className="flex-1 h-full flex flex-col justify-end items-center group relative">
                  <div
                    className="w-full bg-primary/10 rounded-t-lg group-hover:bg-primary transition-all relative"
                    style={{ height: `${h}%` }}
                  >
                    <div className="absolute -top-8 left-1/2 -translate-x-1/2 bg-foreground text-background text-[8px] font-bold px-2 py-1 rounded opacity-0 group-hover:opacity-100 transition-opacity whitespace-nowrap z-10">
                      {h} Handovers
                    </div>
                  </div>
                  <span className="text-[9px] font-bold text-muted-foreground uppercase tracking-widest mt-4 opacity-40">
                    {['M', 'T', 'W', 'T', 'F', 'S', 'S'][i]}
                  </span>
                </div>
              ))}
            </div>
          </div>

          {/* Quick Audit */}
          <div className="bg-card rounded-xl p-8 lg:p-10 border border-border shadow-sm relative overflow-hidden group font-sans">
            <h3 className="text-base font-bold mb-8 font-serif uppercase tracking-tight text-foreground">
              Cycle Audit
            </h3>
            <div className="space-y-6">
              {[
                { label: 'Revenues', value: '₹12,400', color: 'text-foreground opacity-80' },
                { label: 'Deductions', value: '₹0.00', color: 'text-foreground opacity-50' },
                { label: 'Net Disbursal', value: '₹12,400', color: 'text-foreground font-bold' }
              ].map((row, i) => (
                <div key={i} className="flex justify-between items-center border-b border-border/50 pb-4">
                  <span className="text-[9px] font-bold uppercase tracking-[0.2em] text-muted-foreground">{row.label}</span>
                  <span className={`text-[10px] font-bold ${row.color}`}>{row.value}</span>
                </div>
              ))}
            </div>
            <button 
              onClick={onDownloadLedger}
              className="w-full mt-10 h-11 bg-muted/20 border border-border text-foreground hover:bg-primary/10 hover:text-primary rounded-xl flex items-center justify-center gap-3 text-[9px] font-bold uppercase tracking-widest transition-all"
            >
              Download Tax Ledger
            </button>
          </div>
        </div>
      </Container>
    </div>
  );
};

export default RiderStatsPage;
