version: '3.8'

services:
  app:
    build: .
    ports:
      - "5001:5001"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      # Add other secrets here or use .env file
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
